library(httr)
library(jsonlite)
library(dplyr)
library(glue)
my_apikey <- Sys.getenv("pwd")
url <- modify_url(url = "http://dataservice.accuweather.com", path = glue("/locations/v1/topcities/100?apikey={my_apikey}&language=en-us&details=false"))
resp <- GET(url)
country_list <- resp %>% .$content %>% rawToChar() %>% fromJSON()
head(country_list, 10)